### ISSUE TITLE
pull access denied for danwahlin/node

### ISSUE THREAD

**Issue by kurdi89** [DanWahlin/NodeExpressMongoDBDockerApp#2]
`λ docker run -d -p 3000:3000 --link my-mongodb:mongodb --name nodeapp danwahlin/node
Unable to find image 'danwahlin/node:latest' locally
docker: Error response from daemon: pull access denied for danwahlin/node, repository does not exist or may require 'docker login'.
See 'docker run --help'.`

**Comment by DanWahlin** [comment]
You'll need to build your own image. I don't keep the images up in Docker hub due to the software changing so much.
